### ISSUE TITLE
Scripting error running under IE11

### ISSUE THREAD

**Issue by jswindell** [hrkymkw/Blip#1]
This was found while running the site within Visual Studio 2015 RC1.

![image](https://cloud.githubusercontent.com/assets/722549/8297855/1fdb0026-192f-11e5-84d6-2ffd2744bbdb.png)

**Comment by hrkymkw** [comment]
Fixed the issue by removing the following in Login.cshtml:

<script src="~/Scripts/jquery-1.10.2.min.js"></script>

<script src="~/Scripts/bootstrap.min.js"></script>

Now, they are included only in _Layout.cshtml, along with the konami.
