### ISSUE TITLE
Inactive User access

### ISSUE THREAD

**Issue by jswindell** [hrkymkw/Blip#10]
After updating the "admin" User Active status to Inactive, I was still able to log into the system:

![image](https://cloud.githubusercontent.com/assets/722549/8298419/98a36d16-1936-11e5-863c-766fefb08875.png)

**Comment by hrkymkw** [comment]
Fixed it by checking at the time of logging in if the user active value is set to true.
For now, the message returned when an inactive user tries to login is left the same as when an invalid combination of username and password are supplied. Should we inform the user for the inactive user account state, and ask the user to contact the admin? How do most apps deal with this kind of scenario?
