### ISSUE TITLE
"Create Message" button and URL querystring

### ISSUE THREAD

**Issue by jswindell** [hrkymkw/Blip#14]
Is it safe to assume creating a message would involve the authenticated user?

What's with the URL querystring: "Home/Message?sender=admin"

**Comment by hrkymkw** [comment]
Yes. I noticed that, and was wondering if I should removed that parameter.
For now, I left it in the URL, and even if you change the sender in the URL, it will be forced back to the authenticated user.

**Comment by hrkymkw** [comment]
Removed the sender parameter.
