### ISSUE TITLE
Account and Admin purposes are confusing

### ISSUE THREAD

**Issue by jswindell** [hrkymkw/Blip#15]
Is is safe to assume, even not being granted administrative rights, that I be afforded to view the account information of myself and others?

Suggestion: look into making the "Admin" section an Area (https://msdn.microsoft.com/en-us/library/ee671793%28v=vs.100%29.aspx)

**Comment by hrkymkw** [comment]
Implemented Area Admin
Commit: d18d2539e8411cf871b851e350f1930e4f096e51
