### ISSUE TITLE
Mixed Target Frameworks

### ISSUE THREAD

**Issue by jswindell** [hrkymkw/Blip#2]
The web project is targeted for .NET 4.6, however, the dependent packages are mixed with earlier versions:

![image](https://cloud.githubusercontent.com/assets/722549/8297916/ea04cd1e-192f-11e5-8efc-18608d76c9c1.png)

**Comment by ssiko** [comment]
I changed them all to 'net46', deleted the packages folder, then rebuilt, and ran with no issues. Not sure if that is sufficient here...

**Comment by jswindell** [comment]
Well, seeing that the web.config remained intact, that should be it!

**Comment by ssiko** [comment]
Closing...
