### ISSUE TITLE
URLs for "Login" and "Register" aren't abbreviated

### ISSUE THREAD

**Issue by jswindell** [hrkymkw/Blip#4]
As per an earlier requirement, it was requested that the "Login" and "Register" URLs appears as "/login" and "/register," respectively.

I believe this to be a more standard convention.

**Comment by ssiko** [comment]
So what do you suggest? Attribute routing or moving these into another controller?

**Comment by jswindell** [comment]
Have a look into create custom Routes. Hint: check the RouteConfig.cs file.

**Comment by ssiko** [comment]
Yup, good to go...I did not link this up in the layout though. But if you hit /login or /register you will get to the proper controller now.

**Comment by jswindell** [comment]
I have reviewed this change and works as requested.
