### ISSUE TITLE
Required fields on Login page require round-trip for notification

### ISSUE THREAD

**Issue by jswindell** [hrkymkw/Blip#5]
The user inputs on the Login page require a server round-trip to notify the User for required field information.

This would be a good spot for jQuery validation.

**Comment by ssiko** [comment]
Now may be a good time to discuss naming conventions, etc for js files. We need to add js to the Account Create screen. Jquery.validate should work for us here. Just made sense to discuss how we wanted to organize this up front.

**Comment by jswindell** [comment]
I have retested the Login page from POSTing back to the page and has indeed been resolved.
