### ISSUE TITLE
Unintended messages viewable

### ISSUE THREAD

**Issue by jswindell** [hrkymkw/Blip#6]
I can see messages, unintended for me, while signed in as "User1:"

![image](https://cloud.githubusercontent.com/assets/722549/8298153/e1f8bc18-1932-11e5-91ec-82024d542c40.png)

**Comment by ssiko** [comment]
This is fixed but we may want to expand on this and bold the text of our name.

**Comment by ssiko** [comment]
Added said logic this can be closed for now.
