### ISSUE TITLE
No message detail view

### ISSUE THREAD

**Issue by jswindell** [hrkymkw/Blip#7]
I can't seem to view the detailed information of an individual message.

Assuming the current message view becomes less detailed, I should navigate to a more detailed view of the message.

**Comment by ssiko** [comment]
I suggest one of the jqueryui controls with a partial for this one...not sure who wants to step up to the plate....possibly the dialog control, which only needs a div and a model.

**Comment by ssiko** [comment]
Added the start of this using the Jquery UI dialog.

**Comment by ssiko** [comment]
var messageBody = $($(this).parent().children()[4]).html();

Just wanted to also post this line of Jquery :)

**Comment by jswindell** [comment]
I like that you added a slick, inline message view, however,

> ...I should [be able to] navigate to a more detailed view of the message.

**Comment by jswindell** [comment]
This was never completed (to expectations) and being closed due to staleness of project (over a year).
