### ISSUE TITLE
User Name management violation

### ISSUE THREAD

**Issue by jswindell** [hrkymkw/Blip#8]
I was able to create a new User with an already presented UserName--in this case, "user7:"

![image](https://cloud.githubusercontent.com/assets/722549/8298258/7869a666-1934-11e5-93a3-c62e7063792a.png)

**Comment by hrkymkw** [comment]
Added an unique index on User.UserName.
If duplicate user names already exist, they need to be manually removed in the DB before running "Update-database" for the new change to take effect in the local DB.
